### ISSUE TITLE
 memory sanitizer: incorect propagation of uninitialized bits 2

### ISSUE THREAD

**Issue by kriskwiatkowski** [google/sanitizers#1430] opened 2021-07-09 06:10 UTC
In the following code, I emulate the value ``sign`` as uninitialized (by poisoning). During execution, the program branches and prints which branch was taken. Branching depends on the least significant bit of the value ``sign``. As ``sign`` is uninitialized, the conditional jump should trigger UUM.

```
#include <stddef.h>
#include <stdio.h>
#include <stdint.h>

#if defined(VALGRIND)
#include <valgrind/valgrind.h>
#include <valgrind/memcheck.h>
#define POISON(v,vsize) VALGRIND_MAKE_MEM_UNDEFINED(v,vsize)
#define SHADOW(v,vsize)
#else
#include <sanitizer/msan_interface.h>
#define POISON(v,vsize) __msan_allocated_memory(v,vsize)
#define SHADOW(v,vsize) __msan_dump_shadow(v,vsize)
#endif

void test(int argc) {
    // emulate random value of sign
    uint16_t sign = argc & 1;
    uint16_t s;

    POISON(&sign, 2);
    sign = sign & 1;

    s = (-sign);
    s >>= 15;

    if (s==0) {
        printf("branch A taken\n");
    } else {
        printf("branch B taken\n");
    }
}

int main(int argc, const char* argv[]) {
    printf("NUM ARGS=%d\n", argc);
	test(argc);
}
```
The test function starts with assigning value ``0`` or ``1`` to the ``sign`` variable. This is done to show that the execution of the program does depend on the value of ``sign``. 
Then the ``sign`` variable is poisoned, which sets all shadow bits to ``FF FF``. The next logical ``and`` operation ensures only one shadow bit is set (least significant). 

In the next step, the value of ``sign`` is negated and assigned to the value ``s``. Here is where shadow bit propagation logic seems not to work correctly. Usually (x86,arm,riscv,...) negation uses two complements to calculate negation, hence this operation is equal to ``~sign + 1``. Note that in case ``sign=0`` the unary one's complement operation ``~`` will flip all the bits making value of sign equal to ``sign=0xFFFF``. This shouldn't affect state of shadow bits. BUT, next operation ``+1`` flips all the bits back. Hence we have a situation in which one uninitialized bit affects state of all the others. Currently this operation doesn't seem to trigger propagation of shadow bits, but probably (IMHO) it should.

In the next step program executes a branch depending on most significant bit of ``s``. Here we see that value of most significant bit of ``s`` depends on value of least significant bit of ``sign``. The ``if`` statement should trigger UUM.

## Compilation and run:

```
clang -O2 -fsanitize=memory -fsanitize-memory-track-origins=2 -fno-omit-frame-pointer -fno-optimize-sibling-calls test.c

```

Execution:

```
> ./a.     ./a.out a
NUM ARGS=2
branch A taken
kris@qsden 7:22 ~ 

> ./a.out   
NUM ARGS=1
branch B taken

```

Note:
Valgrind reports unconditional jump in this case:
```
kris@qsden 7:27 ~ 
> gcc -O2 -g -DVALGRIND test.c
kris@qsden 7:28 ~ 
> valgrind ./a.out              
==654828== Memcheck, a memory error detector
==654828== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==654828== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==654828== Command: ./a.out
==654828== 
NUM ARGS=1
==654828== Conditional jump or move depends on uninitialised value(s)
==654828==    at 0x1091FD: test (test.c:27)
==654828==    by 0x109079: main (test.c:36)
==654828== 
branch B taken
==654828== 
==654828== HEAP SUMMARY:
==654828==     in use at exit: 0 bytes in 0 blocks
==654828==   total heap usage: 1 allocs, 1 frees, 1,024 bytes allocated
==654828== 
==654828== All heap blocks were freed -- no leaks are possible
==654828== 
==654828== Use --track-origins=yes to see where uninitialised values come from
==654828== For lists of detected and suppressed errors, rerun with: -s
==654828== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
kris@qsden 7:28 ~ 

```

**Comment by vitalybuka** [comment] 2021-07-09 06:18
I suspect it's also duplicate of #1424

**Comment by kriskwiatkowski** [comment] 2021-07-09 06:25
Could be. Don't know MSan that well.

**Comment by vitalybuka** [comment] 2021-07-09 06:31
Thanks for reporting, if we decide to fix this we will find examples from duplicates.
However, from the msan code it does not look like oversight but rather a deliberate traid-off to have fewer instructions. 
Duplicate of  #1424

**Closed by vitalybuka** 2021-07-09 06:31 UTC
