### ISSUE TITLE
MSan does not detect read to uninitialized stack variable

### ISSUE THREAD

**Issue by mrigger** [google/sanitizers#781] opened 2017-03-16 16:20 UTC
Consider the following program:
```c
#include <stdio.h>

int print(int val) {
    printf("%d\n", val);
    return val;
}

int main() {
  int i;
  for (int j = 0; j < 1000; j++) {
      i = i + 1;
  }
  print(i);
  return 0;
}
```
I compiled the program with `clang-3.9 -g -fsanitize=memory` and executed it. I expected that ` i = i + 1`, the call to `print`, `printf`, or returning the value would result in an unitialized read. However, the program executed without errors. A way to trigger an error would be to replace `return 0` in `main` by `return i`.

I found a similar bug while executing a simple [checksum implementation](https://github.com/4Federiz/Checksum/pull/1) with Safe Sulong. MSan found the error, but at a later location than I expected.

Is this the expected behavior? Am I missing some flags?

**Comment by eugenis** [comment] 2017-03-16 20:55
Yes, that's a known problem.
Duplicate of issue #718.

**Comment by mrigger** [comment] 2017-03-16 21:15
Sorry, I saw that I already stumbled upon this problem before (see #742).

**Closed** 2017-03-22 15:39 UTC
