### ISSUE TITLE
thread sanitizer is not showing data race

### ISSUE THREAD

**Issue by gshirishfree** [google/sanitizers#632] opened 2015-12-03 23:42 UTC
I tried the program given  http://clang.llvm.org/docs/ThreadSanitizer.html#usage

small_race.c

#include <pthread.h>
int Global;
void *Thread1(void *x) {
  Global = 42;
  return x;
}
int main() {
  pthread_t t;
  pthread_create(&t, NULL, Thread1, NULL);
  Global = 43;
  pthread_join(t, NULL);
  return Global;
}
compilation

$ clang -fsanitize=thread -g -pthread -O1 small_race.c
$./a.out  ==> No error it's passing successfully

I tried to create 2 more thread and also try to sleep in one of thread then also it's passing. I am using Debian OS. I am doing something wrong ?

**Comment by kcc** [comment] 2015-12-03 23:46
Works for me. Which version of clang are you using?

**Comment by gshirishfree** [comment] 2015-12-04 01:11
clang version 3.0-6.2

**Comment by kcc** [comment] 2015-12-04 01:13
seems *very* old.  
If you run the fresh clang from trunk it will tell you: 
clang version 3.8.0 (trunk 254461)

Closing. Please reopen if you observe this with the fresh clang

**Closed by kcc** 2015-12-04 01:13 UTC

**Comment by gshirishfree** [comment] 2015-12-05 00:12
Ok. i'll try. But I think if it's compiling fine with 3.0-6.2 it should work, I mean it should show me warning.

**Comment by kcc** [comment] 2015-12-05 00:16
I frankly don't know what 3.0-6.2 is. Is that LLVM 3.0? 
 tsan has appeared in clang since ~ 3.4.
3.0 may not have a proper flag parser, or whatever.
Anyway, anything that does not reproduce on the current trunk is more or less irrelevant for this bug tracker.

**Comment by gshirishfree** [comment] 2015-12-07 19:34
Hi kcc,

I tried with gcc 4.9 but still it's not showing any warning or output

shirish@shirish-VirtualBox:~/thread_sanit$ uname -r
3.19.0-25-generic

:~$ dpkg --list | grep compiler
ii  g++-4.9                   4.9.3-8ubuntu2~14.04                                amd64        GNU C++ compiler

:~/thread_sanit$ g++ -ltsan -lasan -pthread small_race.c -o small_race
:~/thread_sanit$ ./small_race ==> No Error no warning

Do you think I need to set some flag I am sure I am doing something wrong ?

Thanks

**Comment by vonosmas** [comment] 2015-12-07 19:35
Pass -fsanitize=thread to compile your code with TSan.

**Comment by gshirishfree** [comment] 2015-12-07 19:46
I am getting below error

:~/thread_sanit$ g++ -fsanitize=thread -ltsan -g -pthread -pie -fPIC -o small_race small_race.c
/tmp/cc6ZOiO9.o: In function `Thread1(void*)':
/home/shirish/thread_sanit/small_race.c:6: undefined reference to `__tsan_func_entry'
/home/shirish/thread_sanit/small_race.c:7: undefined reference to `__tsan_read4'
/home/shirish/thread_sanit/small_race.c:8: undefined reference to `__tsan_write4'
/home/shirish/thread_sanit/small_race.c:9: undefined reference to `__tsan_read4'
/home/shirish/thread_sanit/small_race.c:10: undefined reference to `__tsan_func_exit'
/tmp/cc6ZOiO9.o: In function `main':
/home/shirish/thread_sanit/small_race.c:13: undefined reference to `__tsan_func_entry'
/home/shirish/thread_sanit/small_race.c:14: undefined reference to `__tsan_write4'
/home/shirish/thread_sanit/small_race.c:16: undefined reference to `__tsan_write4'
/home/shirish/thread_sanit/small_race.c:20: undefined reference to `__tsan_write4'
/home/shirish/thread_sanit/small_race.c:23: undefined reference to `__tsan_write4'
/home/shirish/thread_sanit/small_race.c:24: undefined reference to `__tsan_read4'
/home/shirish/thread_sanit/small_race.c:25: undefined reference to `__tsan_read8'
/home/shirish/thread_sanit/small_race.c:26: undefined reference to `__tsan_read4'
/home/shirish/thread_sanit/small_race.c:26: undefined reference to `__tsan_func_exit'
/tmp/cc6ZOiO9.o: In function `__static_initialization_and_destruction_0':
/home/shirish/thread_sanit/small_race.c:27: undefined reference to `__tsan_func_entry'
/home/shirish/thread_sanit/small_race.c:27: undefined reference to `__tsan_func_exit'
/tmp/cc6ZOiO9.o: In function `_GLOBAL__sub_I_small_race.c':
/home/shirish/thread_sanit/small_race.c:27: undefined reference to `__tsan_func_entry'
/home/shirish/thread_sanit/small_race.c:27: undefined reference to `__tsan_func_exit'
/tmp/cc6ZOiO9.o: In function `_GLOBAL__sub_I_00099_0_small_race.c':
/home/shirish/thread_sanit/small_race.c:27: undefined reference to `__tsan_init'
collect2: error: ld returned 1 exit status

**Comment by gshirishfree** [comment] 2015-12-07 19:48
OK thanks worked fine by adding -fsanitize=thread

**Comment by gshirishfree** [comment] 2015-12-07 19:56
Just one more question if you want I can open new question.

If I am getting error like FATAL: ThreadSanitizer canot mmap the shadow memory (something is mapped at 0x400000 < 0x7cf000000000)

Why it's showing this and how to debug or resolve this issue ?

**Comment by dvyukov** [comment] 2015-12-07 19:58
Add -fPIE flag during compilation, and -pie flag during linking.

**Comment by gshirishfree** [comment] 2015-12-07 20:35
I add flag you mention but still I am getting error FATAL: ThreadSanitizer canot mmap the shadow memory (something is mapped at 0x400000 < 0x7cf000000000)

**Comment by dvyukov** [comment] 2015-12-07 21:10
@gshirishfree please provide full reproducer.
