### ISSUE TITLE
memory sanitizer: incorect propagation of uninitialized bits

### ISSUE THREAD

**Issue by kriskwiatkowski** [google/sanitizers#1427] opened 2021-07-07 18:54 UTC
In the following code the ``compare_bytes`` function always compares all bits stored in ``a`` with those in ``b``. The ``test`` function marks one bit of the 2-byte variable ``a`` as uninitialized (by using POISON macro and logical shift right). Then a comparison of two values is done and execution of the program depends on the result of the comparison.

```
#include <stddef.h>
#include <stdio.h>
#include <stdint.h>

#if defined(VALGRIND)
#include <valgrind/valgrind.h>
#include <valgrind/memcheck.h>
#define POISON(v,vsize) VALGRIND_MAKE_MEM_UNDEFINED(v,vsize)
#define SHADOW(v,vsize)
#else
#include <sanitizer/msan_interface.h>
#define POISON(v,vsize) __msan_allocated_memory(v,vsize)
#define SHADOW(v,vsize) __msan_dump_shadow(v,vsize)
#endif

//  Returns 0 if p==q, otherwise 1
uint8_t compare_bytes(const void *a, const void *b, size_t n) {
    const uint8_t *pa = (uint8_t *) a, *pb = (uint8_t *) b;
    uint8_t r = 0;

    while (n--) { r |= *pa++ ^ *pb++; }
    r   = (r >> 1) - r; // most significant bit == 1 iff r!=0
    r >>= 7;
    return r;
}

void test() {
    uint16_t a;
    uint16_t clean = 0;
    uint8_t t;

    a = 0xffff;
    POISON(&a, 2);
    a >>= 15; // ensure only one bit is poisoned

    t = compare_bytes(&clean,&a,2);
    SHADOW(&t, 1);
    if (t !=0 ) {
        printf("branch taken\n");
    }
}

int main() {
	test();
}
```

The ``compare_bytes``, as implemented, should propagate bits of shadow memory used for storing a state of ``a`` to shadow memory used to store the state of ``r``. The ``SHADOW`` uses ``__msan_dump_shadow`` to print uninitialized bits. The ``if(t != 0)`` should trigger UUM (use of uninitialized memory). 

Compilation:
```
> clang -O2 -fsanitize=memory -fsanitize-memory-track-origins=2 -fno-omit-frame-pointer -fno-optimize-sibling-calls test.c

```
Execution:
```
> ./a.     ./a.out 
00 
branch taken
```

Memory sanitiser incorrectly reports a state of uninitialized memory and doesn't trigger UUM.

__Note__
* Commenting out the call to ``SHADOW`` will trigger UUM (only if compiled with -O2)
* Valgrind's memcheck correctly reports UUM

Issue is similar to #1424 but it doesn't depend on optimization level used during compilation

I'm using clang 12.0.0 on a x86-64 linux (x86_64-pc-linux-gnu)

**Comment by vitalybuka** [comment] 2021-07-09 06:18
Duplicate of #1424

**Closed by vitalybuka** 2021-07-09 06:18 UTC
